export enum ETypeInput {
  TEXT = 'text',
  PASSWORD = 'password',
  EMAIL = 'email',
  EMAIL_PASSWORD = 'email-password',
  NUMBER = 'number',
  DATE = 'date',
  TIME = 'time',
  DATETIME_LOCAL = 'datetime-local',
  SEARCH = 'search',
  TEL = 'tel',
  URL = 'url',
  COLOR = 'color',
  MONTH = 'month',
  WEEK = 'week',
  FILE = 'file',
  CHECKBOX = 'checkbox',
  RADIO = 'radio',
  RANGE = 'range',
  HIDDEN = 'hidden',
  TEXTAREA = 'textarea',
  SELECT = 'select',
  MULTISELECT = 'multiselect',
  AUTOCOMPLETE = 'autocomplete',
  SWITCH = 'switch',
  CALENDAR = 'calendar',
  DROPDOWN = 'dropdown',
  CHIPS = 'chips',
  TOGGLE = 'toggle',
  OTP = 'otp',
  CURRENCY = 'currency',
  KNOB = 'knob',
  BADGE = 'badge',
  DECIMAL = 'decimal',
  IMAGE = 'image',

  COMPONENT = 'component'
}
